project:
  type: website
  output-dir: docs
  resources:
    - image_playground

website:
  title: "Weyland Joyner"
  navbar:
    left:
      - href: /
        text: Home
      - href: /paper_reproductions/
        text: Paper Reproductions
      - href: /image_playground/
        text: Image Playground

format:
  html:
    theme: cosmo
    toc: true
